### PR TITLE
Update 'preprint' to 'paper' and link in index.Rmd

### PR DESCRIPTION
**Pull request by nakucher**
Noticed this had the preprint linked - updated with the paper!

### CODE REVIEW

**Comment by avahoffman** [comment]
Thanks @nakucher !

**Comment by KatherineCox** [comment]
@cansavvy is this breaking because @nakucher isn't on this repo (i.e. she's submitting the PR from her fork rather than from a branch owned by jhudsl?)  And if so, is that a problem with OTTR, or is it just this repo? 

https://github.com/jhudsl/AnVIL_Book_Getting_Started/runs/7309200828?check_suite_focus=true

**Comment by cansavvy** [comment]
Correct. Unfortunately there's not a great way for the OTTR checks to work from forked repos. 

Easiest work around is to copy over file changes to a branch on this repository.

**Review by KatherineCox — APPROVED** [review]
Thanks for updating this!

**Pull request merged**
