### PR TITLE
Open existing workspace

### PR DESCRIPTION
**Pull request by KatherineCox**
Added instructions on how to find and open an existing Workspace (5.1)

Reordered so that Cloning comes before Creating.

Added a caveat to the New Workspace (5.2) and Cloning sections (5.3) - if the PI followed our recommendations, the Data Analyst might not have permission to create their own Workspaces.

Added instructions on how to share your Workspace (5.4).

### CODE REVIEW

**Comment by avahoffman** [comment]
Looks like you might be missing a file? Or have something named differently?
```
Error in file(con, "r") : cannot open the connection
Calls: local ... lapply -> FUN -> knit -> <Anonymous> -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file './_child_workspace_add_members.Rmd': No such file or directory

Execution halted
```

**Comment by KatherineCox** [comment]
Yeah, sorry, this one's not quite ready for review, I switched it from draft so the render steps would run but got pulled away before I could check results. I thought I untagged you, but maybe not.

**Comment by avahoffman** [comment]
@KatherineCox no worries! Just tag me if you want a review later 🙂

**Comment by KatherineCox** [comment]
@avahoffman okay, now it's ready! :)

**Review by avahoffman — APPROVED** [review]
LGTM!

**Pull request merged**
