### PR TITLE
test adding new chapter

### PR DESCRIPTION
**Pull request by KatherineCox**
Investigating problem previewing new chapters

Added a new chapter that should show up as Appendix H

### CODE REVIEW

**Comment by cansavvy** [comment]
Here's where I'm at: when I run the steps of the render-preview GHA manually and locally, the new-chapter.html file gets created no problem. But for some reason that file isn't making it onto the preview branch (in this case `preview-127`.

**Comment by cansavvy** [comment]
@KatherineCox, made some adjustments to the git add step and it appears to be fixed. Is it correct to assume you don't want this fake chapter actually added? If so I'll delete the fake chapter and merge the fixes (I'll also be adding these changes to the OTTR_Template repo itself of course).

**Comment by KatherineCox** [comment]
Yep, go ahead and delete the fake chapter. Thanks for looking in to this!

**Comment by KatherineCox** [comment]
@cansavvy if I just delete the fake chapter, am I okay to merge this?  Or alternatively, close this PR and just merge the automatic PR from OTTR_Template updates?

**Comment by cansavvy** [comment]
Yes! Sorry about the delay!

**Pull request closed without merging**
